SECRET_KEY = 'SECRET_KEY'
DEBUG = True

MONGODB_DB = 'partygo'
MONGODB_HOST = 'HOST'
MONGODB_PORT = 22222
MONGODB_USERNAME = 'USERNAME'
MONGODB_PASSWORD = 'PASSWORD'

PROJECT_ID = 'PROJECT_ID'
CLOUD_STORAGE_BUCKET = 'STORAGE_BUCKET'
